---
layout: post
title: Deploy on Kubernetes with Helm
date: 2023-06-14
tags: wildfly kubernetes helm
synopsis: How to deploy WildFly applications on Kubernetes with Helm.
author: marcosgopen
---

https://helm.sh[Helm] is a tool that helps define, install and upgrade complex applications on Kubernetes clusters.

In this post, we will use the Wildfly chart from https://github.com/wildfly/wildfly-charts/[https://github.com/wildfly/wildfly-charts/] to deploy a simple Wildfly application:

* Create a simple Java application
* use the wildfly-maven-plugin's image goal to create a Docker image straight from Maven
* push that image in a container registry (eg quay.io or ghcr.io)
* use Helm to deploy that image in a Kubernetes cluster (e.g. using kind)

Note: for the purpose of this article we will use 'kind' as a tool for running local Kubernetes cluster (see more about https://kind.sigs.k8s.io/[kind]).
## Prerequisites
* Helm[https://helm.sh/docs/intro/install/] installed on your machine
* Docker[https://docs.docker.com/engine/install/] or Podman[https://podman.io/docs/installation] installed on your machine
* A kubernetes cluster available, i.e. installed kind[https://kind.sigs.k8s.io/] on your machine
* a container registry account[https://quay.io/] where to push and pull your image (eg quay.io or ghcr.io)

## Create a simple Java application

We will use one WildFly quickstart as an example: https://github.com/wildfly/quickstart/tree/main/helloworld[helloworld].

[source,nowrap]
----
$ git clone https://github.com/wildfly/quickstart
$ cd quickstart/helloworld 
----

## Install Helm and have access to a Kubernetes cluster.

Please refer to https://helm.sh/docs/intro/install/[Installing Helm] page to install Helm in your environment.

We will use https://kind.sigs.k8s.io/[kind] as our Kubernetes cluster.

## Install Helm Repository for WildFly Chart

The `wildfly` Chart can be installed from the https://docs.wildfly.org/wildfly-charts/ repository

[source,nowrap]
----
$ helm repo add wildfly https://docs.wildfly.org/wildfly-charts/
"wildfly" has been added to your repositories
$ helm search repo wildfly
NAME                  	CHART VERSION	APP VERSION	DESCRIPTION                                       
wildfly/wildfly       	2.3.1        	           	Build and Deploy WildFly applications on OpenShift
wildfly/wildfly-common	2.1.0        	           	A library chart for WildFly-based applications  
----

## Make sure our application pom contains the wildfly-maven-plugin and maven-war-plugin plugins 

In our helloworld quickstart the maven-war-plugin is already present (recommanded version is 3.2.3).
Please be sure to have an updated version of it under the build section of the pom:

[source,nowrap]
----
  <build>
...
    <plugins>
...
      <plugin>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.2.3</version>
         <executions>
          <execution>
            <id>default-war</id>
            <phase>package</phase>
            <goals>
              <goal>war</goal>
            </goals>
            <configuration>
              <archive>
                <index>true</index>
                <manifest>
                  <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
                  <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                </manifest>
              </archive>
              <failOnMissingWebXml>false</failOnMissingWebXml>
            </configuration>
          </execution>
        </executions>
      </plugin>
...
    </plugins>
...
  </build>
----

In our helloworld quickstart the wildfly-maven-plugin plugin is already present under the 'openshift' profile.
Add it if you don't have it in your pom.xml (the profile id could be whatever you want).

[source,nowrap]
----
<profiles>
...
        <profile>
            <id>openshift</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.wildfly.plugins</groupId>
                        <artifactId>wildfly-maven-plugin</artifactId>
                        <version>${version.wildfly.maven.plugin}</version>
                        <configuration>
                            <feature-packs>
                                <feature-pack>
                                    <location>org.wildfly:wildfly-galleon-pack:${version.server}</location>
                                </feature-pack>
                                <feature-pack>
                                    <location>org.wildfly.cloud:wildfly-cloud-galleon-pack:${version.cloud.fp}</location>
                                </feature-pack>
                            </feature-packs>
                            <layers>
                                <layer>cloud-server</layer>
                            </layers>
                            <filename>${project.artifactId}-${project.version}.war</filename>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>package</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
...
    </profiles>    
----

## Build the docker image with the wildfly-maven-plugin plugin 

Note: In this example we use 'docker', 'podman' works as well.

[source,nowrap]
----
 $ mvn package
 $ mvn wildfly:image -Popenshift
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< org.wildfly.quickstarts:helloworld >-----------------
[INFO] Building Quickstart: helloworld 29.0.0.Alpha1-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- wildfly-maven-plugin:4.1.0.Final:image (default-cli) @ helloworld ---
[INFO] A server already exists in ~quickstart/helloworld/target/server, skipping image of org.wildfly.quickstarts:helloworld
[INFO] Generating Dockerfile ~quickstart/helloworld/target/Dockerfile from base image quay.io/wildfly/wildfly-runtime:latest
[INFO] Building application image helloworld:latest using docker.
[INFO] Executing the following command to build application image: 'docker build -t helloworld:latest .'
[INFO] #1 [internal] load build definition from Dockerfile
[INFO] #1 transferring dockerfile: 305B done
[INFO] #1 DONE 0.0s
[INFO] 
[INFO] #2 [internal] load .dockerignore
[INFO] #2 transferring context: 2B done
[INFO] #2 DONE 0.0s
[INFO] 
[INFO] #3 [internal] load metadata for quay.io/wildfly/wildfly-runtime:latest
[INFO] #3 DONE 1.0s
[INFO] 
[INFO] #4 [internal] load build context
[INFO] #4 transferring context: 291.04kB 0.1s done
[INFO] #4 DONE 0.1s
[INFO] 
[INFO] #5 [1/4] FROM quay.io/wildfly/wildfly-runtime:latest@sha256:841dcb723e1dd55c86c5762a19f190967c7f5382c2b1896ab34e033091b2d1b1
[INFO] #5 resolve quay.io/wildfly/wildfly-runtime:latest@sha256:841dcb723e1dd55c86c5762a19f190967c7f5382c2b1896ab34e033091b2d1b1 0.0s done
[INFO] #5 sha256:841dcb723e1dd55c86c5762a19f190967c7f5382c2b1896ab34e033091b2d1b1 529B / 529B done
[INFO] #5 sha256:ad0bc1ba34b50c2d5e19fc990664a029d3507d6564ffdfe2ccca8830f47a03b5 596B / 596B done
[INFO] #5 sha256:5e080efee10e501789f7a6a30f3686bc811cbe72927e3f7cb6cc20137e9e93a4 20.00kB / 20.00kB done
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 0B / 39.36MB 0.1s
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 0B / 105.39MB 0.1s
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 2.10MB / 39.36MB 2.6s
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 4.19MB / 39.36MB 3.7s
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 6.29MB / 39.36MB 4.4s
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 8.39MB / 39.36MB 5.1s
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 2.10MB / 105.39MB 5.1s
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 10.49MB / 39.36MB 5.8s
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 12.58MB / 39.36MB 6.3s
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 14.68MB / 39.36MB 6.7s
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 16.78MB / 39.36MB 7.0s
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 18.87MB / 39.36MB 7.5s
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 22.02MB / 39.36MB 7.8s
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 24.12MB / 39.36MB 8.1s
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 8.39MB / 105.39MB 8.1s
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 26.21MB / 39.36MB 8.3s
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 28.31MB / 39.36MB 8.6s
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 31.46MB / 39.36MB 9.3s
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 34.60MB / 39.36MB 9.8s
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 36.70MB / 39.36MB 10.1s
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 38.80MB / 39.36MB 10.5s
[INFO] #5 sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 39.36MB / 39.36MB 10.7s done
[INFO] #5 extracting sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 14.68MB / 105.39MB 11.0s
[INFO] #5 extracting sha256:dc73c550c444377a03ac72705bd8c77fbd391d58fd3e9e497372dd839a80b525 0.8s done
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 20.97MB / 105.39MB 12.8s
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 27.26MB / 105.39MB 13.9s
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 34.60MB / 105.39MB 14.9s
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 40.89MB / 105.39MB 15.5s
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 47.19MB / 105.39MB 16.0s
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 53.48MB / 105.39MB 16.9s
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 59.77MB / 105.39MB 17.6s
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 66.06MB / 105.39MB 18.3s
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 72.35MB / 105.39MB 20.2s
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 79.69MB / 105.39MB 21.3s
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 85.98MB / 105.39MB 23.2s
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 92.27MB / 105.39MB 24.4s
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 98.57MB / 105.39MB 25.4s
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 104.86MB / 105.39MB 26.8s
[INFO] #5 sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 105.39MB / 105.39MB 26.9s done
[INFO] #5 extracting sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 0.1s
[INFO] #5 extracting sha256:14ec73a097d67af31d535345860e178f85b1eedd00d5281f403215f536888254 2.0s done
[INFO] #5 DONE 29.1s
[INFO] 
[INFO] #6 [2/4] COPY --chown=jboss:root server /opt/server
[INFO] #6 DONE 0.5s
[INFO] 
[INFO] #7 [3/4] RUN chmod -R ug+rwX /opt/server
[INFO] #7 DONE 2.0s
[INFO] 
[INFO] #8 [4/4] COPY --chown=jboss:root helloworld.war /opt/server/standalone/deployments/helloworld.war
[INFO] #8 DONE 0.1s
[INFO] 
[INFO] #9 exporting to image
[INFO] #9 exporting layers
[INFO] #9 exporting layers 0.8s done
[INFO] #9 writing image sha256:6d404b584da25d85816212c8de49184e86d9f29a427b436fbf44ee8513abe0a4 done
[INFO] #9 naming to docker.io/library/helloworld:latest
[INFO] #9 naming to docker.io/library/helloworld:latest done
[INFO] #9 DONE 0.8s
[INFO] Successfully built application image helloworld:latest
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  34.784 s
[INFO] Finished at: 2023-06-14T17:27:40+02:00
[INFO] ------------------------------------------------------------------------

----
And then make sure you have it in your docker images
[source,nowrap]
----
 $ docker images
REPOSITORY                        TAG                     IMAGE ID       CREATED          SIZE
helloworld                        latest                  6d404b584da2   32 seconds ago   686MB

----

## Push the just created image to a container registry (eg quay.io, ghcr.io or hub.docker.com)

In this article we will use Quay.io as a container registry.
If you don't have an account you can start a free trial on https://quay.io/[https://quay.io/] or create an account on https://hub.docker.com/[dockerhub]
Login to your container registry, see how to get started https://docs.quay.io/solution/getting-started.html[here]
Then tag the new image with the proper format 'quay.io/username/reponame'
Please be sure to replace the 'username' (your account username) and the 'reponame' (your image name) accordingly!
If you use ghcr.io you have to change 'quay.io/username/reponame' with `ghcr.io/NAMESPACE/IMAGE_NAME`
If you use hub.docker.com you have to change 'quay.io/username/reponame' with `username/image_name`



[source]
----
$ docker login quay.io
$ docker tag helloworld quay.io/username/helloworld
----

Check that your image has been tagged:

[source]
----
$ docker images
helloworld                          latest                  6d404b584da2   56 minutes ago   686MB
quay.io/username/helloworld   latest                  6d404b584da2   56 minutes ago   686MB

----
Push the image in your registry:

[source]
----
$ docker push quay.io/username/helloworld
Using default tag: latest
The push refers to repository [quay.io/username/helloworld]
ad91a69a4efb: Pushed 
f454069ae0d4: Pushed 
b21a08aa50a4: Pushed 
4fc9e93f9cc1: Pushed 
55ea6d5a354e: Pushed 
latest: digest: sha256:1d72e7b4f8dd75414a2b1dc8da3505906b0211ac6962e871b84f2c8ead43cb3a size: 1377
----
Now your image is available in your container registry (in my case it is available at https://quay.io/repository/rh_ee_msappegr/helloworld)
Note: please make sure your registry is public in order to pull it from the cluster or create a docker-registry secret[https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/] .

## Create the YAML value file under the charts folder

In our example the charts folder already exists under quickstart/helloworld/charts, so move in that directory and create a file named values.yaml

[source]
----
$ cd charts 
$ touch values.yaml
----
 and paste the following inside the values.yaml

[source]
----
image:
  name: quay.io/rh_ee_msappegr/helloworld # change it with the image you have just pushed
build:
  enabled: false # The build part is not needed since we have already built our application with the wildfly-maven-plugin plugin
deploy:
  route:
    enabled: false # the route could be enabled only for Openshift  clusters
----


## Deploy the Application on Kubernetes

Once the `wildfly` Chart is added, we can install a Helm *release* by using the `helm install` command with the name of the release as well as a YAML configuration file that contains all the settings to build and deploy the application:

[source]
----
$ helm install helloworld-app \
    wildfly/wildfly \
    -f charts/values.yaml

NAME: helloworld-app
LAST DEPLOYED: Wed Jun 14 18:45:38 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
To follow the deployment of your application, run:

$ kubectl get deployment helloworld-app -w
----

As you can read above, the output of the `helm install` command contains instructions to follow the installation of the application.

We can watch its deployment by running:

[source]
----
$ kubectl get deployment helloworld-app -w
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
helloworld-app   1/1     1            1           30s
----

The application is now available and we can query it (you might need to wait some seconds to see our application up and running).
In order to reach your application from the browser you might port-forward port 8080 to your host:

[source]
----
$ kubectl port-forward $(oc get pod -l app.kubernetes.io/instance=helloworld-app -o name) 8080:8080
Forwarding from 127.0.0.1:8080 -> 8080
...
----
`Note: If your application has a different name you can retrieve your pod name by executing:
`$ kubectl get pod`
Then in the output you will see your pod name.
Now you can execute:
`$ kubectl port-forward your_pod_name 8080:8080`

Now open your browser and browse URL 'localhost:8080', your application will respond: Hello World!
Alternately you can curl it from your terminal:

[source]
----
$ curl localhost:8080
<!--
    JBoss, Home of Professional Open Source
    Copyright 2015, Red Hat, Inc. and/or its affiliates, and individual
    contributors by the @authors tag. See the copyright.txt in the
    distribution for a full listing of individual contributors.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!-- Plain HTML page that kicks us into the app -->

<html>
    <head>
        <meta http-equiv="Refresh" content="0; URL=HelloWorld">
    </head>
</html>
----

The application is up and running.

## Conclusion
It is possible to run you application with very simple steps.
All is necessary is:
* to have the wildfly-maven-plugin plugin in your root pom
* to generate your image and to push it to your registry
* to install the helm chart

## More about Helm Chart

More documentation about it can be found at https://github.com/wildfly/wildfly-charts/blob/main/charts/wildfly/README.md[`wildfly` Chart documentation].

## More information

* https://helm.sh[Helm] - The package manager for Kubernetes]
* https://github.com/wildfly/wildfly-charts[wildfly-charts Project Page]
* https://github.com/wildfly/wildfly-charts/blob/main/charts/wildfly/README.md[`wildfly` Chart documentation]

